feature/Task3AddhyperlinktoLoginPage
ROAHIT/webapplications pull request #2
Opened 2021-02-08 07:02 UTC by ROAHIT

2021-02-08 13:10 UTC, bharathreo29 commented on homepage.html
>          h1
Put all the style code into a "Style" folder and make reference from there. Study about the methods to implement css codes.

2021-02-08 13:13 UTC, bharathreo29 requested changes

2021-02-08 13:13 UTC, bharathreo29 commented on homepage.html
> +            top: 30%;
Put all the style code into a "Style" folder and make reference from there. Study about the methods to implement css codes.

2021-02-08 13:13 UTC, bharathreo29 commented on homepage.html
> +            <script type="text/javascript">
Put javascript code in a separate folder and refer the script from there. Study about the methods to invoke javascript code inside a html file.

2021-02-09 16:12 UTC, closed without merging

2021-02-09 16:13 UTC, ROAHIT commented
created another feature branch from a branch instead of main branch